#include "foundation_concepts.hpp"
#include <vector>
#include <string>
#include <unordered_map>

namespace brain19 {

namespace {

struct ConceptSeed {
    std::string label;
    std::string definition;
    EpistemicType type;
    double trust;
};

struct RelationSeed {
    std::string source_label;
    std::string target_label;
    RelationType type;
    double weight;
};

void store_seeds(LongTermMemory& ltm,
                 const std::vector<ConceptSeed>& seeds,
                 std::unordered_map<std::string, ConceptId>& lmap) {
    for (const auto& s : seeds) {
        auto id = ltm.store_concept(s.label, s.definition,
            EpistemicMetadata(s.type, EpistemicStatus::ACTIVE, s.trust));
        lmap[s.label] = id;
    }
}

void store_rels(LongTermMemory& ltm,
                const std::vector<RelationSeed>& seeds,
                const std::unordered_map<std::string, ConceptId>& lmap) {
    for (const auto& r : seeds) {
        auto si = lmap.find(r.source_label);
        auto ti = lmap.find(r.target_label);
        if (si != lmap.end() && ti != lmap.end())
            ltm.add_relation(si->second, ti->second, r.type, r.weight);
    }
}

thread_local std::unordered_map<std::string, ConceptId> g_lmap;

const std::vector<ConceptSeed> T1 = {
    {"Entity","The most general category; anything that exists or can be conceived.",EpistemicType::DEFINITION,0.99},
    {"Object","A concrete or abstract thing that can be perceived or thought about.",EpistemicType::DEFINITION,0.99},
    {"Action","A process or activity performed by an agent.",EpistemicType::DEFINITION,0.99},
    {"Property","An attribute or quality of an entity.",EpistemicType::DEFINITION,0.99},
    {"Relation","A connection or association between two or more entities.",EpistemicType::DEFINITION,0.99},
    {"Event","Something that happens at a particular time and place.",EpistemicType::DEFINITION,0.99},
    {"State","A condition or mode of being at a given time.",EpistemicType::DEFINITION,0.99},
    {"Process","A series of actions or changes leading to a result.",EpistemicType::DEFINITION,0.99},
    {"Abstract","Existing in thought or as an idea, not physically.",EpistemicType::DEFINITION,0.99},
    {"Concrete","Having a physical, tangible existence.",EpistemicType::DEFINITION,0.99},
    {"Physical","Relating to the material world and natural forces.",EpistemicType::DEFINITION,0.99},
    {"Mental","Relating to the mind and cognitive processes.",EpistemicType::DEFINITION,0.99},
    {"Social","Relating to society and interactions between individuals.",EpistemicType::DEFINITION,0.99},
    {"Temporal","Relating to time.",EpistemicType::DEFINITION,0.99},
    {"Spatial","Relating to space and position.",EpistemicType::DEFINITION,0.99},
    {"Category","A class or division of entities sharing common attributes.",EpistemicType::DEFINITION,0.99},
    {"Type","A subcategory or classification within a category.",EpistemicType::DEFINITION,0.99},
    {"Instance","A specific example or occurrence of a type.",EpistemicType::DEFINITION,0.99},
    {"Concept","An abstract idea or mental representation.",EpistemicType::DEFINITION,0.99},
    {"Definition","A precise statement of the meaning of a word or concept.",EpistemicType::DEFINITION,0.99},
    {"Cause","Something that produces an effect or result.",EpistemicType::DEFINITION,0.99},
    {"Effect","A result produced by a cause.",EpistemicType::DEFINITION,0.99},
    {"System","A set of interacting components forming a complex whole.",EpistemicType::DEFINITION,0.99},
    {"Structure","The arrangement and organisation of parts within a whole.",EpistemicType::DEFINITION,0.99},
    {"Function","The purpose or role something serves.",EpistemicType::DEFINITION,0.98},
    {"Pattern","A recurring arrangement or sequence.",EpistemicType::DEFINITION,0.98},
    {"Change","The act or instance of becoming different.",EpistemicType::DEFINITION,0.98},
    {"Quantity","An amount or number of something.",EpistemicType::DEFINITION,0.98},
    {"Quality","A characteristic or attribute of something.",EpistemicType::DEFINITION,0.98},
    {"Value","The worth, importance, or usefulness of something.",EpistemicType::DEFINITION,0.98},
    {"Truth","Correspondence with fact or reality.",EpistemicType::DEFINITION,0.98},
    {"Knowledge","Justified true belief; information held with confidence.",EpistemicType::DEFINITION,0.98},
    {"Information","Data that has been processed into meaningful form.",EpistemicType::DEFINITION,0.98},
    {"Meaning","The significance or sense conveyed by something.",EpistemicType::DEFINITION,0.98},
    {"Evidence","Facts or observations supporting a conclusion.",EpistemicType::DEFINITION,0.98},
    {"Rule","A prescribed directive governing behaviour or structure.",EpistemicType::DEFINITION,0.98},
    {"Law","A fundamental principle governing a domain.",EpistemicType::DEFINITION,0.98},
    {"Principle","A fundamental truth or proposition serving as a foundation.",EpistemicType::DEFINITION,0.98},
    {"Model","A simplified representation of a system or phenomenon.",EpistemicType::DEFINITION,0.98},
    {"Theory","A well-substantiated explanation of some aspect of the natural world.",EpistemicType::DEFINITION,0.98},
    {"Hypothesis","A proposed explanation made on the basis of limited evidence.",EpistemicType::DEFINITION,0.98},
    {"Fact","Something known to be true based on evidence.",EpistemicType::DEFINITION,0.98},
    {"Measurement","The assignment of a numerical value to a property.",EpistemicType::DEFINITION,0.98},
    {"Unit","A standard quantity used to express a measurement.",EpistemicType::DEFINITION,0.98},
    {"Dimension","A measurable extent such as length, width, or time.",EpistemicType::DEFINITION,0.98},
    {"Boundary","A limit or edge of something.",EpistemicType::DEFINITION,0.97},
    {"Context","The circumstances surrounding an event or statement.",EpistemicType::DEFINITION,0.97},
    {"Scope","The extent or range of something.",EpistemicType::DEFINITION,0.97},
    {"Identity","The set of qualities that make something what it is.",EpistemicType::DEFINITION,0.97},
    {"Existence","The state of having objective reality.",EpistemicType::DEFINITION,0.97},
};

const std::vector<ConceptSeed> T2 = {
    {"Organism","A living individual capable of growth and reproduction.",EpistemicType::DEFINITION,0.98},
    {"Person","A human being.",EpistemicType::DEFINITION,0.99},
    {"Animal","A multicellular organism that feeds on organic matter.",EpistemicType::DEFINITION,0.98},
    {"Plant","A photosynthetic multicellular organism.",EpistemicType::DEFINITION,0.98},
    {"Microorganism","An organism too small to see with the naked eye.",EpistemicType::DEFINITION,0.97},
    {"Place","A particular position or area.",EpistemicType::DEFINITION,0.99},
    {"Country","A sovereign political territory.",EpistemicType::DEFINITION,0.98},
    {"City","A large settlement of people.",EpistemicType::DEFINITION,0.98},
    {"Region","An area with common characteristics.",EpistemicType::DEFINITION,0.98},
    {"Continent","One of the large landmasses on Earth.",EpistemicType::DEFINITION,0.98},
    {"Ocean","A vast body of salt water covering most of Earth.",EpistemicType::DEFINITION,0.98},
    {"Mountain","A large natural elevation of the Earth's surface.",EpistemicType::DEFINITION,0.97},
    {"River","A large natural stream of water flowing to the sea.",EpistemicType::DEFINITION,0.97},
    {"Science","Systematic study of the natural world through observation and experiment.",EpistemicType::DEFINITION,0.99},
    {"Physics","The science of matter, energy, and their interactions.",EpistemicType::DEFINITION,0.99},
    {"Chemistry","The science of substances, their properties, and reactions.",EpistemicType::DEFINITION,0.99},
    {"Biology","The science of living organisms.",EpistemicType::DEFINITION,0.99},
    {"Mathematics","The abstract science of number, quantity, and space.",EpistemicType::DEFINITION,0.99},
    {"Astronomy","The science of celestial objects and the universe.",EpistemicType::DEFINITION,0.98},
    {"Geology","The science of the Earth's physical structure.",EpistemicType::DEFINITION,0.98},
    {"Ecology","The study of organisms and their environment.",EpistemicType::DEFINITION,0.98},
    {"Medicine","The science and practice of diagnosing and treating disease.",EpistemicType::DEFINITION,0.98},
    {"Psychology","The scientific study of the mind and behaviour.",EpistemicType::DEFINITION,0.98},
    {"Economics","The study of production, distribution, and consumption of goods.",EpistemicType::DEFINITION,0.97},
    {"Sociology","The study of human social behaviour and institutions.",EpistemicType::DEFINITION,0.97},
    {"Philosophy","The study of fundamental questions about existence, knowledge, and values.",EpistemicType::DEFINITION,0.98},
    {"Language","A structured system of communication.",EpistemicType::DEFINITION,0.99},
    {"Art","Creative expression of ideas and emotions.",EpistemicType::DEFINITION,0.98},
    {"Music","Organised sound in time.",EpistemicType::DEFINITION,0.98},
    {"Literature","Written works of artistic merit.",EpistemicType::DEFINITION,0.98},
    {"History","The study and record of past events.",EpistemicType::DEFINITION,0.98},
    {"Technology","The application of scientific knowledge for practical purposes.",EpistemicType::DEFINITION,0.99},
    {"Computer","An electronic device for processing data.",EpistemicType::DEFINITION,0.98},
    {"Software","Programs and data that run on a computer.",EpistemicType::DEFINITION,0.98},
    {"Hardware","The physical components of a computer system.",EpistemicType::DEFINITION,0.98},
    {"Algorithm","A step-by-step procedure for solving a problem.",EpistemicType::DEFINITION,0.98},
    {"Network","A system of interconnected nodes or devices.",EpistemicType::DEFINITION,0.97},
    {"Internet","A global system of interconnected computer networks.",EpistemicType::DEFINITION,0.98},
    {"Database","An organised collection of structured data.",EpistemicType::DEFINITION,0.97},
    {"Society","A group of individuals sharing a common culture.",EpistemicType::DEFINITION,0.98},
    {"Government","The system by which a state is governed.",EpistemicType::DEFINITION,0.98},
    {"Culture","The ideas, customs, and social behaviour of a group.",EpistemicType::DEFINITION,0.98},
    {"Education","The process of receiving or giving systematic instruction.",EpistemicType::DEFINITION,0.98},
    {"Religion","A system of faith and worship.",EpistemicType::DEFINITION,0.97},
    {"Weather","The state of the atmosphere at a place and time.",EpistemicType::DEFINITION,0.97},
    {"Climate","Long-term average weather patterns in a region.",EpistemicType::DEFINITION,0.97},
    {"Ecosystem","A community of organisms and their physical environment.",EpistemicType::DEFINITION,0.98},
    {"Time","The indefinite continued progress of existence.",EpistemicType::DEFINITION,0.99},
    {"Space","The boundless extent in which objects exist.",EpistemicType::DEFINITION,0.99},
    {"Matter","Anything that has mass and occupies space.",EpistemicType::DEFINITION,0.99},
    {"Energy","The capacity to do work.",EpistemicType::DEFINITION,0.99},
    {"Food","Substances consumed for nutrition.",EpistemicType::DEFINITION,0.97},
    {"Water","A chemical compound (H2O) essential for life.",EpistemicType::DEFINITION,0.98},
    {"Air","The mixture of gases surrounding the Earth.",EpistemicType::DEFINITION,0.98},
    {"Earth","The planet on which we live.",EpistemicType::DEFINITION,0.99},
    {"Sun","The star at the centre of our solar system.",EpistemicType::DEFINITION,0.99},
    {"Moon","A natural satellite orbiting a planet.",EpistemicType::DEFINITION,0.98},
    {"Star","A luminous celestial body of plasma held together by gravity.",EpistemicType::DEFINITION,0.98},
    {"Planet","A celestial body orbiting a star, massive enough to be round.",EpistemicType::DEFINITION,0.98},
    {"Galaxy","A massive system of stars, gas, and dust bound by gravity.",EpistemicType::DEFINITION,0.98},
    {"Universe","All of space, time, matter, and energy.",EpistemicType::DEFINITION,0.99},
    {"Gravity","The force of attraction between masses.",EpistemicType::FACT,0.99},
    {"Light","Electromagnetic radiation visible to the human eye.",EpistemicType::DEFINITION,0.98},
    {"Sound","Vibrations travelling through a medium, perceived by hearing.",EpistemicType::DEFINITION,0.98},
    {"Heat","Thermal energy transferred due to temperature difference.",EpistemicType::DEFINITION,0.98},
    {"Electricity","The flow of electric charge.",EpistemicType::DEFINITION,0.98},
    {"Magnetism","A force caused by moving electric charges.",EpistemicType::DEFINITION,0.98},
    {"Wave","A disturbance that transfers energy through a medium.",EpistemicType::DEFINITION,0.97},
    {"Pressure","Force per unit area.",EpistemicType::DEFINITION,0.98},
    {"Temperature","A measure of the average kinetic energy of particles.",EpistemicType::DEFINITION,0.98},
    {"Speed","The rate of change of position.",EpistemicType::DEFINITION,0.98},
    {"Acceleration","The rate of change of velocity.",EpistemicType::DEFINITION,0.98},
    {"Force","An interaction that changes the motion of an object.",EpistemicType::DEFINITION,0.99},
    {"Mass","A measure of the amount of matter in an object.",EpistemicType::DEFINITION,0.99},
    {"Volume","The amount of three-dimensional space occupied by an object.",EpistemicType::DEFINITION,0.98},
    {"Density","Mass per unit volume.",EpistemicType::DEFINITION,0.98},
    {"Velocity","Speed in a given direction.",EpistemicType::DEFINITION,0.98},
    {"Momentum","The product of mass and velocity.",EpistemicType::DEFINITION,0.98},
    {"Frequency","The number of occurrences of a repeating event per unit time.",EpistemicType::DEFINITION,0.97},
    {"Wavelength","The distance between successive crests of a wave.",EpistemicType::DEFINITION,0.97},
    {"Amplitude","The maximum displacement of a wave from its rest position.",EpistemicType::DEFINITION,0.97},
    {"Color","The visual perception of different wavelengths of light.",EpistemicType::DEFINITION,0.97},
    {"Emotion","A complex psychological state involving subjective experience.",EpistemicType::DEFINITION,0.96},
    {"Consciousness","Awareness of internal and external existence.",EpistemicType::DEFINITION,0.96},
    {"Intelligence","The ability to acquire and apply knowledge and skills.",EpistemicType::DEFINITION,0.97},
    {"Memory_Faculty","The cognitive faculty of encoding, storing, and retrieving information.",EpistemicType::DEFINITION,0.97},
    {"Perception","The organisation and interpretation of sensory information.",EpistemicType::DEFINITION,0.97},
    {"Reasoning","The process of drawing conclusions from evidence.",EpistemicType::DEFINITION,0.97},
    {"Logic","The systematic study of valid inference.",EpistemicType::DEFINITION,0.98},
    {"Probability","A measure of the likelihood that an event will occur.",EpistemicType::DEFINITION,0.98},
    {"Statistics","The collection, analysis, and interpretation of numerical data.",EpistemicType::DEFINITION,0.97},
    {"Experiment","A procedure carried out to test a hypothesis.",EpistemicType::DEFINITION,0.98},
    {"Observation","The act of perceiving and recording phenomena.",EpistemicType::DEFINITION,0.98},
    {"Data","Facts and statistics collected for analysis.",EpistemicType::DEFINITION,0.97},
    {"Communication","The exchange of information between entities.",EpistemicType::DEFINITION,0.98},
    {"Symbol","Something that represents or stands for something else.",EpistemicType::DEFINITION,0.97},
    {"Number","A mathematical object used to count, measure, and label.",EpistemicType::DEFINITION,0.99},
    {"Set","A well-defined collection of distinct objects.",EpistemicType::DEFINITION,0.99},
};

const std::vector<ConceptSeed> T4 = {
    {"Atom","The smallest unit of a chemical element.",EpistemicType::DEFINITION,0.99},
    {"Element","A substance consisting of atoms with the same atomic number.",EpistemicType::DEFINITION,0.99},
    {"Molecule","Two or more atoms bonded together.",EpistemicType::DEFINITION,0.99},
    {"Compound","A substance formed from two or more elements chemically bonded.",EpistemicType::DEFINITION,0.98},
    {"Ion","An atom or molecule with a net electric charge.",EpistemicType::DEFINITION,0.98},
    {"Electron","A subatomic particle with a negative charge.",EpistemicType::DEFINITION,0.99},
    {"Proton","A subatomic particle with a positive charge.",EpistemicType::DEFINITION,0.99},
    {"Neutron","A subatomic particle with no charge.",EpistemicType::DEFINITION,0.99},
    {"Nucleus","The dense central region of an atom.",EpistemicType::DEFINITION,0.99},
    {"Chemical_Bond","An attraction between atoms allowing formation of compounds.",EpistemicType::DEFINITION,0.98},
    {"Reaction","A process in which substances are transformed.",EpistemicType::DEFINITION,0.98},
    {"Catalyst","A substance that increases reaction rate without being consumed.",EpistemicType::DEFINITION,0.98},
    {"Solution","A homogeneous mixture of two or more substances.",EpistemicType::DEFINITION,0.97},
    {"Acid","A substance that donates protons or accepts electron pairs.",EpistemicType::DEFINITION,0.97},
    {"Base","A substance that accepts protons or donates electron pairs.",EpistemicType::DEFINITION,0.97},
    {"Oxidation","Loss of electrons in a chemical reaction.",EpistemicType::DEFINITION,0.97},
    {"Reduction","Gain of electrons in a chemical reaction.",EpistemicType::DEFINITION,0.97},
    {"Entropy","A measure of disorder or randomness in a system.",EpistemicType::DEFINITION,0.98},
    {"Thermodynamics","The branch of physics dealing with heat and energy transfer.",EpistemicType::DEFINITION,0.98},
    {"Electromagnetism","The interaction of electric and magnetic fields.",EpistemicType::DEFINITION,0.98},
    {"Quantum_Mechanics","The branch of physics dealing with subatomic phenomena.",EpistemicType::DEFINITION,0.97},
    {"Relativity","Einstein's theories relating space, time, and gravity.",EpistemicType::DEFINITION,0.97},
    {"Field","A region in which a force or effect is exerted.",EpistemicType::DEFINITION,0.97},
    {"Particle","A minute portion of matter.",EpistemicType::DEFINITION,0.98},
    {"Photon","A quantum of electromagnetic radiation.",EpistemicType::DEFINITION,0.98},
    {"Spectrum","The range of electromagnetic radiation by wavelength.",EpistemicType::DEFINITION,0.97},
    {"Cell","The basic structural and functional unit of life.",EpistemicType::DEFINITION,0.99},
    {"DNA","Deoxyribonucleic acid; carries genetic instructions.",EpistemicType::DEFINITION,0.99},
    {"RNA","Ribonucleic acid; involved in protein synthesis.",EpistemicType::DEFINITION,0.98},
    {"Gene","A unit of heredity encoding a functional product.",EpistemicType::DEFINITION,0.99},
    {"Chromosome","A structure of DNA and protein carrying genes.",EpistemicType::DEFINITION,0.98},
    {"Protein","A macromolecule composed of amino acid chains.",EpistemicType::DEFINITION,0.98},
    {"Enzyme","A protein that catalyses biochemical reactions.",EpistemicType::DEFINITION,0.98},
    {"Metabolism","The set of chemical reactions sustaining life.",EpistemicType::DEFINITION,0.98},
    {"Photosynthesis","Conversion of light energy into chemical energy by organisms.",EpistemicType::DEFINITION,0.98},
    {"Respiration","The metabolic process of releasing energy from nutrients.",EpistemicType::DEFINITION,0.98},
    {"Evolution","Change in heritable characteristics of populations over generations.",EpistemicType::DEFINITION,0.99},
    {"Natural_Selection","Differential survival and reproduction of organisms.",EpistemicType::DEFINITION,0.98},
    {"Species","A group of organisms capable of interbreeding.",EpistemicType::DEFINITION,0.98},
    {"Mutation","A change in the DNA sequence of an organism.",EpistemicType::DEFINITION,0.98},
    {"Heredity","The passing of traits from parents to offspring.",EpistemicType::DEFINITION,0.98},
    {"Virus","A submicroscopic infectious agent that replicates inside cells.",EpistemicType::DEFINITION,0.97},
    {"Bacteria","Single-celled prokaryotic microorganisms.",EpistemicType::DEFINITION,0.98},
    {"Tissue","A group of cells with a similar structure and function.",EpistemicType::DEFINITION,0.97},
    {"Organ","A structure composed of tissues performing a specific function.",EpistemicType::DEFINITION,0.97},
    {"Nervous_System","The network of nerve cells that coordinates actions.",EpistemicType::DEFINITION,0.97},
    {"Immune_System","The biological defence system against pathogens.",EpistemicType::DEFINITION,0.97},
    {"Brain","The organ that serves as the centre of the nervous system.",EpistemicType::DEFINITION,0.98},
    {"Neuron","A nerve cell that transmits electrical signals.",EpistemicType::DEFINITION,0.98},
    {"Integer","A whole number, positive, negative, or zero.",EpistemicType::DEFINITION,0.99},
    {"Real_Number","A number on the continuous number line.",EpistemicType::DEFINITION,0.99},
    {"Complex_Number","A number with a real and an imaginary part.",EpistemicType::DEFINITION,0.98},
    {"Variable","A symbol representing an unknown or changeable value.",EpistemicType::DEFINITION,0.98},
    {"Equation","A statement asserting the equality of two expressions.",EpistemicType::DEFINITION,0.99},
    {"Inequality","A relation expressing that one quantity is less or greater.",EpistemicType::DEFINITION,0.98},
    {"Math_Function","A mapping from inputs to outputs.",EpistemicType::DEFINITION,0.99},
    {"Limit","The value a function approaches as input approaches a point.",EpistemicType::DEFINITION,0.98},
    {"Derivative","The rate of change of a function with respect to a variable.",EpistemicType::DEFINITION,0.98},
    {"Integral","The accumulation of quantities over a range.",EpistemicType::DEFINITION,0.98},
    {"Proof","A logical argument establishing the truth of a theorem.",EpistemicType::DEFINITION,0.99},
    {"Theorem","A statement proven on the basis of axioms.",EpistemicType::DEFINITION,0.99},
    {"Axiom","A statement accepted as true without proof.",EpistemicType::DEFINITION,0.99},
    {"Algebra","The branch of mathematics dealing with symbols and rules.",EpistemicType::DEFINITION,0.98},
    {"Geometry","The branch of mathematics dealing with shapes and space.",EpistemicType::DEFINITION,0.98},
    {"Calculus","The branch of mathematics studying continuous change.",EpistemicType::DEFINITION,0.98},
    {"Topology","The study of properties preserved under continuous deformation.",EpistemicType::DEFINITION,0.97},
    {"Graph","A set of vertices connected by edges.",EpistemicType::DEFINITION,0.97},
    {"Matrix","A rectangular array of numbers.",EpistemicType::DEFINITION,0.97},
    {"Vector","A quantity with both magnitude and direction.",EpistemicType::DEFINITION,0.98},
    {"Scalar","A quantity with only magnitude.",EpistemicType::DEFINITION,0.98},
    {"Infinity","A concept of something without bound.",EpistemicType::DEFINITION,0.97},
    {"Zero","The integer denoting no quantity; the additive identity.",EpistemicType::DEFINITION,0.99},
    {"Pi","The ratio of a circle's circumference to its diameter.",EpistemicType::FACT,0.99},
    {"Turing_Machine","An abstract model of computation.",EpistemicType::DEFINITION,0.98},
    {"Complexity","A measure of resources required to solve a problem.",EpistemicType::DEFINITION,0.97},
    {"Recursion","A process that calls itself as part of its definition.",EpistemicType::DEFINITION,0.98},
    {"Boolean","A data type with two values: true and false.",EpistemicType::DEFINITION,0.98},
    {"Bit","The smallest unit of digital information (0 or 1).",EpistemicType::DEFINITION,0.99},
    {"Byte","A unit of digital information equal to 8 bits.",EpistemicType::DEFINITION,0.99},
    {"Encryption","The process of encoding information for security.",EpistemicType::DEFINITION,0.97},
    {"Operating_System","Software that manages computer hardware and software resources.",EpistemicType::DEFINITION,0.97},
    {"Programming_Language","A formal language for writing computer programs.",EpistemicType::DEFINITION,0.98},
    {"Artificial_Intelligence","The simulation of intelligent behaviour by machines.",EpistemicType::DEFINITION,0.97},
    {"Machine_Learning","A subset of AI where systems learn from data.",EpistemicType::DEFINITION,0.97},
    {"Neural_Network","A computing model inspired by biological neural networks.",EpistemicType::DEFINITION,0.97},
};

const std::vector<RelationSeed> R3 = {
    {"Object","Entity",RelationType::IS_A,0.95},
    {"Action","Entity",RelationType::IS_A,0.95},
    {"Property","Entity",RelationType::IS_A,0.95},
    {"Relation","Entity",RelationType::IS_A,0.95},
    {"Event","Entity",RelationType::IS_A,0.95},
    {"State","Entity",RelationType::IS_A,0.95},
    {"Process","Action",RelationType::IS_A,0.90},
    {"Category","Abstract",RelationType::IS_A,0.90},
    {"Concept","Abstract",RelationType::IS_A,0.90},
    {"Person","Organism",RelationType::IS_A,0.95},
    {"Animal","Organism",RelationType::IS_A,0.95},
    {"Plant","Organism",RelationType::IS_A,0.95},
    {"Microorganism","Organism",RelationType::IS_A,0.95},
    {"Organism","Entity",RelationType::IS_A,0.90},
    {"City","Place",RelationType::IS_A,0.95},
    {"Country","Place",RelationType::IS_A,0.95},
    {"Region","Place",RelationType::IS_A,0.95},
    {"Continent","Place",RelationType::IS_A,0.95},
    {"Ocean","Place",RelationType::IS_A,0.90},
    {"Mountain","Place",RelationType::IS_A,0.90},
    {"River","Place",RelationType::IS_A,0.90},
    {"Place","Entity",RelationType::IS_A,0.90},
    {"Physics","Science",RelationType::IS_A,0.95},
    {"Chemistry","Science",RelationType::IS_A,0.95},
    {"Biology","Science",RelationType::IS_A,0.95},
    {"Mathematics","Science",RelationType::IS_A,0.95},
    {"Astronomy","Science",RelationType::IS_A,0.95},
    {"Geology","Science",RelationType::IS_A,0.95},
    {"Ecology","Science",RelationType::IS_A,0.95},
    {"Medicine","Science",RelationType::IS_A,0.90},
    {"Psychology","Science",RelationType::IS_A,0.90},
    {"Economics","Science",RelationType::IS_A,0.85},
    {"Sociology","Science",RelationType::IS_A,0.85},
    {"Science","Knowledge",RelationType::IS_A,0.90},
    {"Computer","Technology",RelationType::IS_A,0.90},
    {"Software","Technology",RelationType::IS_A,0.90},
    {"Internet","Network",RelationType::IS_A,0.90},
    {"Network","System",RelationType::IS_A,0.85},
    {"Algorithm","Process",RelationType::IS_A,0.85},
    {"Database","Software",RelationType::IS_A,0.85},
    {"Molecule","Entity",RelationType::IS_A,0.90},
    {"Atom","Entity",RelationType::IS_A,0.90},
    {"Element","Entity",RelationType::IS_A,0.90},
    {"Compound","Molecule",RelationType::IS_A,0.85},
    {"Ion","Atom",RelationType::IS_A,0.80},
    {"Electron","Particle",RelationType::IS_A,0.95},
    {"Proton","Particle",RelationType::IS_A,0.95},
    {"Neutron","Particle",RelationType::IS_A,0.95},
    {"Photon","Particle",RelationType::IS_A,0.95},
    {"Cell","Entity",RelationType::IS_A,0.90},
    {"Gene","Entity",RelationType::IS_A,0.85},
    {"Protein","Molecule",RelationType::IS_A,0.90},
    {"Enzyme","Protein",RelationType::IS_A,0.90},
    {"Virus","Entity",RelationType::IS_A,0.85},
    {"Bacteria","Microorganism",RelationType::IS_A,0.90},
    {"Tissue","Entity",RelationType::IS_A,0.85},
    {"Organ","Entity",RelationType::IS_A,0.85},
    {"Neuron","Cell",RelationType::IS_A,0.90},
    {"Integer","Real_Number",RelationType::IS_A,0.95},
    {"Real_Number","Complex_Number",RelationType::IS_A,0.95},
    {"Algebra","Mathematics",RelationType::IS_A,0.95},
    {"Geometry","Mathematics",RelationType::IS_A,0.95},
    {"Calculus","Mathematics",RelationType::IS_A,0.95},
    {"Topology","Mathematics",RelationType::IS_A,0.90},
    {"Statistics","Mathematics",RelationType::IS_A,0.90},
    {"Logic","Mathematics",RelationType::IS_A,0.85},
    {"Probability","Mathematics",RelationType::IS_A,0.90},
    {"Machine_Learning","Artificial_Intelligence",RelationType::IS_A,0.90},
    {"Neural_Network","Machine_Learning",RelationType::IS_A,0.85},
    {"Programming_Language","Language",RelationType::IS_A,0.80},
    {"Turing_Machine","Model",RelationType::IS_A,0.85},
    {"Art","Culture",RelationType::IS_A,0.85},
    {"Music","Art",RelationType::IS_A,0.90},
    {"Literature","Art",RelationType::IS_A,0.90},
    {"Nucleus","Atom",RelationType::PART_OF,0.95},
    {"Electron","Atom",RelationType::PART_OF,0.90},
    {"Proton","Nucleus",RelationType::PART_OF,0.95},
    {"Neutron","Nucleus",RelationType::PART_OF,0.95},
    {"Gene","Chromosome",RelationType::PART_OF,0.90},
    {"Chromosome","Cell",RelationType::PART_OF,0.90},
    {"DNA","Chromosome",RelationType::PART_OF,0.90},
    {"Cell","Tissue",RelationType::PART_OF,0.85},
    {"Tissue","Organ",RelationType::PART_OF,0.85},
    {"Organ","Organism",RelationType::PART_OF,0.85},
    {"Neuron","Nervous_System",RelationType::PART_OF,0.85},
    {"Brain","Nervous_System",RelationType::PART_OF,0.90},
    {"City","Country",RelationType::PART_OF,0.85},
    {"Country","Continent",RelationType::PART_OF,0.80},
    {"Software","Computer",RelationType::PART_OF,0.80},
    {"Hardware","Computer",RelationType::PART_OF,0.85},
    {"Bit","Byte",RelationType::PART_OF,0.90},
    {"Person","Intelligence",RelationType::HAS_PROPERTY,0.85},
    {"Person","Consciousness",RelationType::HAS_PROPERTY,0.85},
    {"Person","Emotion",RelationType::HAS_PROPERTY,0.85},
    {"Organism","Metabolism",RelationType::HAS_PROPERTY,0.90},
    {"Atom","Mass",RelationType::HAS_PROPERTY,0.95},
    {"Wave","Frequency",RelationType::HAS_PROPERTY,0.95},
    {"Wave","Wavelength",RelationType::HAS_PROPERTY,0.95},
    {"Wave","Amplitude",RelationType::HAS_PROPERTY,0.95},
    {"Matter","Mass",RelationType::HAS_PROPERTY,0.95},
    {"Matter","Volume",RelationType::HAS_PROPERTY,0.95},
    {"Matter","Density",RelationType::HAS_PROPERTY,0.90},
    {"Light","Speed",RelationType::HAS_PROPERTY,0.90},
    {"Light","Wavelength",RelationType::HAS_PROPERTY,0.90},
    {"Light","Color",RelationType::HAS_PROPERTY,0.85},
    {"Sound","Frequency",RelationType::HAS_PROPERTY,0.90},
    {"Sound","Amplitude",RelationType::HAS_PROPERTY,0.90},
    {"Object","Mass",RelationType::HAS_PROPERTY,0.85},
    {"Object","Volume",RelationType::HAS_PROPERTY,0.80},
    {"Place","Spatial",RelationType::HAS_PROPERTY,0.85},
    {"Event","Temporal",RelationType::HAS_PROPERTY,0.85},
    {"Force","Acceleration",RelationType::CAUSES,0.95},
    {"Heat","Temperature",RelationType::CAUSES,0.85},
    {"Gravity","Force",RelationType::CAUSES,0.90},
    {"Mutation","Evolution",RelationType::CAUSES,0.80},
    {"Natural_Selection","Evolution",RelationType::CAUSES,0.90},
    {"Catalyst","Reaction",RelationType::ENABLES,0.90},
    {"Enzyme","Reaction",RelationType::ENABLES,0.90},
    {"Energy","Process",RelationType::ENABLES,0.80},
    {"DNA","Heredity",RelationType::ENABLES,0.90},
    {"Gene","Protein",RelationType::ENABLES,0.85},
    {"Photosynthesis","Energy",RelationType::CAUSES,0.85},
    {"Respiration","Energy",RelationType::CAUSES,0.85},
    {"Electricity","Magnetism",RelationType::CAUSES,0.85},
    {"Evidence","Theory",RelationType::SUPPORTS,0.90},
    {"Experiment","Hypothesis",RelationType::SUPPORTS,0.90},
    {"Observation","Fact",RelationType::SUPPORTS,0.85},
    {"Axiom","Theorem",RelationType::SUPPORTS,0.95},
    {"Proof","Theorem",RelationType::SUPPORTS,0.95},
    {"Data","Statistics",RelationType::SUPPORTS,0.85},
    {"Energy","Force",RelationType::SIMILAR_TO,0.60},
    {"Speed","Velocity",RelationType::SIMILAR_TO,0.85},
    {"Hypothesis","Theory",RelationType::SIMILAR_TO,0.70},
    {"Acid","Base",RelationType::SIMILAR_TO,0.65},
    {"Oxidation","Reduction",RelationType::SIMILAR_TO,0.70},
    {"DNA","RNA",RelationType::SIMILAR_TO,0.75},
    {"Weather","Climate",RelationType::SIMILAR_TO,0.65},
    {"Algebra","Geometry",RelationType::SIMILAR_TO,0.60},
    {"Physics","Chemistry",RelationType::SIMILAR_TO,0.65},
    {"Biology","Medicine",RelationType::SIMILAR_TO,0.70},
    {"Psychology","Sociology",RelationType::SIMILAR_TO,0.65},
    {"Hypothesis","Experiment",RelationType::TEMPORAL_BEFORE,0.80},
    {"Observation","Hypothesis",RelationType::TEMPORAL_BEFORE,0.75},
    {"Data","Information",RelationType::TEMPORAL_BEFORE,0.70},
};

} // anonymous namespace

void FoundationConcepts::seed_all(LongTermMemory& ltm) {
    g_lmap.clear();
    seed_tier1_ontology(ltm);
    seed_tier2_categories(ltm);
    seed_tier4_science(ltm);
    seed_tier3_relations(ltm);
}

void FoundationConcepts::seed_tier1_ontology(LongTermMemory& ltm) {
    store_seeds(ltm, T1, g_lmap);
}

void FoundationConcepts::seed_tier2_categories(LongTermMemory& ltm) {
    store_seeds(ltm, T2, g_lmap);
}

void FoundationConcepts::seed_tier3_relations(LongTermMemory& ltm) {
    store_rels(ltm, R3, g_lmap);
}

void FoundationConcepts::seed_tier4_science(LongTermMemory& ltm) {
    store_seeds(ltm, T4, g_lmap);
}

size_t FoundationConcepts::concept_count() {
    return T1.size() + T2.size() + T4.size();
}

size_t FoundationConcepts::relation_count() {
    return R3.size();
}

} // namespace brain19
