"""Brain19 Code Assembly Engine.

Takes a pipeline sequence (ordered step IDs + parameter overrides) and
generates a complete main.cpp with correct includes, initialization, and
steps in the right order.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from .templates import TEMPLATES, StepTemplate


@dataclass
class PipelineStep:
    step_id: str
    enabled: bool = True
    params: dict[str, str] = field(default_factory=dict)


@dataclass
class PipelineConfig:
    steps: list[PipelineStep] = field(default_factory=list)
    data_dir: str = "brain19_data/"
    enable_persistence: bool = True
    seed_foundation: bool = True


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

_MAIN_HEADER = """\
// ═══════════════════════════════════════════════════════════════════════════
// Brain19 — Generated Thinking Pipeline
// Auto-generated by Brain19 Pipeline Editor
// ═══════════════════════════════════════════════════════════════════════════

#include "core/brain19_app.hpp"
{includes}
#include <iostream>
#include <string>
#include <cstring>
#include <chrono>
#include <algorithm>
"""

_MAIN_PREAMBLE = """
static void print_usage(const char* prog) {{
    std::cout << "Usage: " << prog << " [options] [command] [args...]\\n\\n";
    std::cout << "Options:\\n";
    std::cout << "  --data-dir <path>      Data directory (default: brain19_data/)\\n";
    std::cout << "  --no-persistence       Disable persistence\\n";
    std::cout << "  --no-foundation        Skip foundation seeding\\n";
    std::cout << "  --help                 Show this help\\n\\n";
    std::cout << "Commands:\\n";
    std::cout << "  ask <question>         Ask a question\\n";
    std::cout << "  status                 Show system status\\n";
    std::cout << "  (none)                 Interactive REPL\\n";
}}

int main(int argc, char* argv[]) {{
    brain19::SystemOrchestrator::Config config;
    config.data_dir = "{data_dir}";
    config.enable_persistence = {enable_persistence};
    config.seed_foundation = {seed_foundation};

    // Pipeline config overrides
{config_overrides}

    // Parse CLI options
    int arg_start = 1;
    for (int i = 1; i < argc; ++i) {{
        if (std::strcmp(argv[i], "--data-dir") == 0 && i + 1 < argc) {{
            config.data_dir = argv[++i];
            arg_start = i + 1;
        }} else if (std::strcmp(argv[i], "--no-persistence") == 0) {{
            config.enable_persistence = false;
            arg_start = i + 1;
        }} else if (std::strcmp(argv[i], "--no-foundation") == 0) {{
            config.seed_foundation = false;
            arg_start = i + 1;
        }} else if (std::strcmp(argv[i], "--help") == 0 || std::strcmp(argv[i], "-h") == 0) {{
            print_usage(argv[0]);
            return 0;
        }} else {{
            arg_start = i;
            break;
        }}
    }}

    brain19::Brain19App app(config);

    if (arg_start < argc) {{
        std::string command = argv[arg_start];
        std::string arg;
        for (int i = arg_start + 1; i < argc; ++i) {{
            if (!arg.empty()) arg += " ";
            arg += argv[i];
        }}
        if (!app.initialize()) {{
            std::cerr << "Failed to initialize Brain19\\n";
            return 1;
        }}
        int result = app.run_command(command, arg);
        app.shutdown();
        return result;
    }}

    return app.run_interactive();
}}
"""


def _substitute_params(code: str, params: dict[str, str], template: StepTemplate) -> str:
    """Replace {{param}} placeholders with actual values."""
    # Build a complete param map: defaults first, then overrides
    param_map: dict[str, str] = {}
    for p in template.params:
        param_map[p.name] = p.default
    param_map.update(params)

    for name, value in param_map.items():
        code = code.replace(f"{{{{{name}}}}}", value)

    return code


def _collect_includes(steps: list[PipelineStep]) -> str:
    """Collect unique includes from all enabled steps."""
    seen: set[str] = set()
    lines: list[str] = []
    for ps in steps:
        if not ps.enabled:
            continue
        tmpl = TEMPLATES.get(ps.step_id)
        if not tmpl:
            continue
        for inc in tmpl.includes:
            if inc not in seen:
                seen.add(inc)
                lines.append(f"#include {inc}")
    return "\n".join(lines)


def _build_config_overrides(steps: list[PipelineStep]) -> str:
    """Build config override lines from pipeline parameters."""
    lines: list[str] = []

    # Map specific params to config fields
    param_config_map = {
        "initial_activation": "config.thinking_config.initial_activation",
        "top_k_salient": "config.thinking_config.top_k_salient",
        "max_relevance_maps": "config.thinking_config.max_relevance_maps",
        "enable_understanding": "config.thinking_config.enable_understanding",
        "enable_kan_validation": "config.thinking_config.enable_kan_validation",
        "enable_curiosity": "config.thinking_config.enable_curiosity",
        "enable_focus_cursor": "config.thinking_config.enable_focus_cursor",
        "enable_gdo": "config.enable_gdo",
    }

    for ps in steps:
        if not ps.enabled:
            continue
        tmpl = TEMPLATES.get(ps.step_id)
        if not tmpl:
            continue
        for p in tmpl.params:
            val = ps.params.get(p.name, p.default)
            config_field = param_config_map.get(p.name)
            if config_field:
                lines.append(f"    {config_field} = {val};")

    return "\n".join(lines) if lines else "    // (using defaults)"


def generate_main_cpp(pipeline: PipelineConfig) -> str:
    """Generate a complete main.cpp from a pipeline configuration."""
    includes = _collect_includes(pipeline.steps)
    config_overrides = _build_config_overrides(pipeline.steps)

    header = _MAIN_HEADER.format(includes=includes)
    body = _MAIN_PREAMBLE.format(
        data_dir=pipeline.data_dir,
        enable_persistence=str(pipeline.enable_persistence).lower(),
        seed_foundation=str(pipeline.seed_foundation).lower(),
        config_overrides=config_overrides,
    )

    return header + body


def parse_current_pipeline(main_cpp_content: str) -> list[dict]:
    """Parse an existing main.cpp and extract the pipeline step sequence.

    Returns a list of step descriptors inferred from comments and code patterns.
    """
    steps: list[dict] = []

    # Match step comments like "// Step 1:", "// Step 2:", "// Step 2.5:", etc.
    step_pattern = re.compile(
        r'//\s*Step\s+(\d+(?:\.\d+)?)\s*:\s*(.+)', re.IGNORECASE
    )

    # Also match config assignments
    config_pattern = re.compile(
        r'config\.thinking_config\.(\w+)\s*=\s*(.+?)\s*;'
    )

    params: dict[str, str] = {}
    for line in main_cpp_content.split("\n"):
        m = config_pattern.search(line)
        if m:
            params[m.group(1)] = m.group(2)

    for line in main_cpp_content.split("\n"):
        m = step_pattern.search(line)
        if m:
            step_num = m.group(1)
            label = m.group(2).strip()

            # Map step numbers to template IDs
            step_id = _step_number_to_id(step_num)
            if step_id:
                steps.append({
                    "step_id": step_id,
                    "step": step_num,
                    "label": label,
                    "enabled": True,
                })

    # Check for optional steps that might be disabled
    for step_id, tmpl in TEMPLATES.items():
        found = any(s["step_id"] == step_id for s in steps)
        if not found and tmpl.step != "BG":
            steps.append({
                "step_id": step_id,
                "step": tmpl.step,
                "label": tmpl.label,
                "enabled": False,
            })

    return steps


def _step_number_to_id(num: str) -> str | None:
    mapping = {
        "1": "stm",
        "2": "spreading",
        "2.5": "cursor",
        "3": "salience",
        "4": "relevance",
        "4-5": "relevance",
        "5": "relevance",
        "6": "paths",
        "7": "curiosity",
        "8": "understanding",
        "9": "kan",
    }
    return mapping.get(num)
